name: Submodule check

on:
  push:
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:

    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Check submodules
      env:
        GH_TOKEN: ${{ github.token }}
      run: ./scripts/ci/require-submodules-on-main-branch.sh
